name: "Tests"
description: "Run depot vote"

runs:
  using: "composite"
  steps:
    - name: Check that the fork is ready
      shell: bash
      run: timeout 30 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' 127.0.0.1 8545

    ## TODO: make real script here
    - name: Run Vote
      shell: bash
      run: npm run omnibus:ci-prepare
      working-directory: depot
