on: [push]
jobs:
  run-tests:
    name: Old scripts repo tests
    runs-on: "ubuntu-latest"
    services:
      fork:
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
        image: feofanov/hardhat-node
        ports:
          - 8545:8545
    timeout-minutes: 120
    steps:
#      - uses: actions/checkout@v3
#        with:
#          path: ./fork
#
#      # run hardhat node in the background
#      - name: Start mainnet fork
#        env:
#          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
#        working-directory: ./fork
#        shell: bash
#        run: |
#          docker compose up -d --build
#
      - name: Wait for the fork to be ready
        shell: bash
        run: timeout 30 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' 127.0.0.1 8545
      - uses: actions/checkout@v3
        with:
          repository: lidofinance/scripts
          ref: feat/hardhat-fork

      # setup and run old repo tests
      - name: Install poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        env:
          POETRY_VERSION: "1.8.2"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install poetry requirements
        shell: bash
        run: poetry install

      - name: Show system info
        shell: bash
        run: |
          echo "Memory and swap:"
          free -h
          echo
          swapon --show
          echo
          df -h
          echo
          echo "CPU units"
          nproc --all

      - name: Run tests
        shell: bash
        run: |
          poetry run brownie networks import network-config.yaml True
          poetry run brownie networks modify mainnet-fork host=http://fork:8545
          poetry run brownie test --network mainnet-fork
