name: Tests runner
on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    services:
      hardhat-node:
        image: ghcr.io/lidofinance/hardhat-node:2.26.0
        ports:
          - 8545:8545
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}

    name: JS tests
    runs-on: ubuntu-latest
    env:
      ALCHEMY_TOKEN: not-so-secret-token

    steps:
      - name: Checkout depot repository
        uses: actions/checkout@v4
        with:
          path: depot

      - name: Setup depot
        uses: ./depot/.github/actions/prepare_depot

      - name: Run unit tests
        run: npm run test
        working-directory: depot
